# This is the config file for our actions
# GitHub Actions lets you specify WHAT happens WHEN a certain event is triggered
# You can also specify on what VM / instance it runs on (default being ubuntu / linux)

# Name of the workflow
name: Git Actions Demo

# Global environments
env:
  NAME: Jim
  
# What triggers this workflow run
on:
   push:
     branches:
     - main
     
# What jobs are part of this workflow
jobs:
  # What is the name of this job
  Actions_demo:
    # What type of instance is our job running on 
    runs-on: ubuntu-latest
    # What are we doing as part of our workflow
    steps:
    # Run a command to get our files on that machine 
    # - run: git clone <git url> 
    - name: Check out repo
      uses: actions/checkout@v3 # Pre build official github action to checkout a repo 

    - name: Create a new file 
      run: touch "My New File.txt"
    - run: ls
    
  build_job:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
      
    # Display the global enviroment variable 
    - run: echo "My name is $NAME"
    
    # Run the buildScript.sh file
    - name: Change the execute permission on the script file so everyone can execute it
      run: chmod +x buildScript.sh
    - name: Run the buid script
      run: ./buildScript.sh $NAME
      
    